### ISSUE TITLE
Laravel 的中大型專案架構

### ISSUE THREAD

**Issue by G-Bruin** [zhaocong6/Reading#2]
```
那我們該怎麼寫呢？別將我們的思維侷限在 MVC 內 :

Model : 僅當成 Eloquent class。
Repository : 輔助 model，處理資料庫邏輯，然後注入到 service。
Service : 輔助 controller，處理商業邏輯，然後注入到 controller。
Controller : 接收 HTTP request，調用其他 service。
Presenter : 處理顯示邏輯，然後注入到 view。
View : 使用 blade 將資料 binding 到 HTML。
```

-  **Presenter 和 View嵌套使用，个人觉得太复杂**

**Comment by zhaocong6** [comment]
Presenter在laravel5.5后框架自带了, 叫做Resources. view我没有使用过, 项目全是前后端分离.  虽然写的时候麻烦, 但是方便维护, 架构也更清晰了

**Comment by Warrens-yg** [comment]
> Presenter在laravel5.5后框架自带了，叫做资源。view我没有使用过，项目全是前替换分离。虽然写的时候麻烦，但是方便维护，架构也更清晰了

我现在在用Laravel5.8，看到了Resource，但是不知道他是如何代替Presenter的，可以详细的告诉我吗？
